//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspose.PDF.Editor.AppResources.Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PdfEditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PdfEditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspose.PDF.Editor.AppResources.Editor.PdfEditorResources", typeof(PdfEditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string DefaultVideoCounter {
            get {
                return ResourceManager.GetString("DefaultVideoCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT1M04S.
        /// </summary>
        public static string DefaultVideoDuration {
            get {
                return ResourceManager.GetString("DefaultVideoDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMoXtaLy64I.
        /// </summary>
        public static string DefaultVideoId {
            get {
                return ResourceManager.GetString("DefaultVideoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Tutorial: How to work with PDF Editor?.
        /// </summary>
        public static string DefaultVideoTitle {
            get {
                return ResourceManager.GetString("DefaultVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, you need to add a file for editing: drag &amp; drop your PDF file or click inside the white area to choose a file. Then edit your file with different tools. When you completed editing the file, you can download the result by clicking the button “Download”..
        /// </summary>
        public static string FAQAnswerFeature1 {
            get {
                return ResourceManager.GetString("FAQAnswerFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This editor works fast. The time of editing depends on your changes to the document..
        /// </summary>
        public static string FAQAnswerFeature2 {
            get {
                return ResourceManager.GetString("FAQAnswerFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course! The download link of the result files will be available instantly after editing. We delete uploaded files after 24 hours and the download links will stop working after this time period. No one has access to your files. PDF editor is absolutely safe..
        /// </summary>
        public static string FAQAnswerFeature3 {
            get {
                return ResourceManager.GetString("FAQAnswerFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, you can use a free editor on any operating system that has a web browser. Our PDF editor works online and does not require any software installation..
        /// </summary>
        public static string FAQAnswerFeature4 {
            get {
                return ResourceManager.GetString("FAQAnswerFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❓ How I can edit PDF?.
        /// </summary>
        public static string FAQQuestionFeature1 {
            get {
                return ResourceManager.GetString("FAQQuestionFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏱️ How long it takes to edit PDF?.
        /// </summary>
        public static string FAQQuestionFeature2 {
            get {
                return ResourceManager.GetString("FAQQuestionFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛡️ Is it safe to edit PDF using a free editor app?.
        /// </summary>
        public static string FAQQuestionFeature3 {
            get {
                return ResourceManager.GetString("FAQQuestionFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💻 Can I edit PDF on Mac OS, Android, or Linux?.
        /// </summary>
        public static string FAQQuestionFeature4 {
            get {
                return ResourceManager.GetString("FAQQuestionFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click inside the file drop area to upload a or drag &amp; drop the file..
        /// </summary>
        public static string HowtoFeature1 {
            get {
                return ResourceManager.GetString("HowtoFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File will be automatically rendered for you to view, edit &amp; download instantly..
        /// </summary>
        public static string HowtoFeature2 {
            get {
                return ResourceManager.GetString("HowtoFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the original or edited file..
        /// </summary>
        public static string HowtoFeature3 {
            get {
                return ResourceManager.GetString("HowtoFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert &amp; download the edited file as PDF..
        /// </summary>
        public static string HowtoFeature4 {
            get {
                return ResourceManager.GetString("HowtoFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert &amp; download the edited file as HTML..
        /// </summary>
        public static string HowtoFeature5 {
            get {
                return ResourceManager.GetString("HowtoFeature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://products.aspose.app/img/pdf/HowToExample/Step1.png.
        /// </summary>
        public static string HowtoImageUrlFeature1 {
            get {
                return ResourceManager.GetString("HowtoImageUrlFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://products.aspose.app/img/pdf/HowToExample/Step2.png.
        /// </summary>
        public static string HowtoImageUrlFeature2 {
            get {
                return ResourceManager.GetString("HowtoImageUrlFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://products.aspose.app/img/pdf/HowToExample/Step2.png.
        /// </summary>
        public static string HowtoImageUrlFeature3 {
            get {
                return ResourceManager.GetString("HowtoImageUrlFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://products.aspose.app/img/pdf/HowToExample/Step2.png.
        /// </summary>
        public static string HowtoImageUrlFeature4 {
            get {
                return ResourceManager.GetString("HowtoImageUrlFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://products.aspose.app/img/pdf/HowToExample/Step2.png.
        /// </summary>
        public static string HowtoImageUrlFeature5 {
            get {
                return ResourceManager.GetString("HowtoImageUrlFeature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your PDF file.
        /// </summary>
        public static string HowtoNameFeature1 {
            get {
                return ResourceManager.GetString("HowtoNameFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your rendered result.
        /// </summary>
        public static string HowtoNameFeature2 {
            get {
                return ResourceManager.GetString("HowtoNameFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download or edited file..
        /// </summary>
        public static string HowtoNameFeature3 {
            get {
                return ResourceManager.GetString("HowtoNameFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert &amp; download the edited file as PDF..
        /// </summary>
        public static string HowtoNameFeature4 {
            get {
                return ResourceManager.GetString("HowtoNameFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert &amp; download the edited file as HTML..
        /// </summary>
        public static string HowtoNameFeature5 {
            get {
                return ResourceManager.GetString("HowtoNameFeature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to view, edit and download a PDF file.
        /// </summary>
        public static string HowtoTitle {
            get {
                return ResourceManager.GetString("HowtoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save edited document to desired format: PDF, Word, HTML and others.
        /// </summary>
        public static string LiFeature1 {
            get {
                return ResourceManager.GetString("LiFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PDF document online without additional software..
        /// </summary>
        public static string LiFeature2 {
            get {
                return ResourceManager.GetString("LiFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add images and texts..
        /// </summary>
        public static string LiFeature3 {
            get {
                return ResourceManager.GetString("LiFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert and manipulate of pages..
        /// </summary>
        public static string LiFeature4 {
            get {
                return ResourceManager.GetString("LiFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PDF document online.
        /// </summary>
        public static string LiFeature5 {
            get {
                return ResourceManager.GetString("LiFeature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try other editors: PDF.
        /// </summary>
        public static string LiFeatureTryOthers {
            get {
                return ResourceManager.GetString("LiFeatureTryOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PDF by adding text, shapes, comments and highlights with advanced WYSIWYG edito. Without registration and captcha. It&apos;s secure and private..
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Editor | Online and Free | Aspose.PDF.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PDF online.
        /// </summary>
        public static string PageTitle1 {
            get {
                return ResourceManager.GetString("PageTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Free, easy-to-use online service to edit PDF!&lt;/strong&gt;&lt;p&gt;Edit PDF files online anytime and from any device. Edit text, add images, freehand draw, and add circles or rectangles with the best Free PDF Editor.&lt;/p&gt;        &lt;strong&gt;Edit PDF Online Free&lt;/strong&gt;&lt;p&gt;There is an opinion that the PDF document cannot be edited. Today it is a myth! Technology has come a long way. Edit the PDF file by the our tool. With a simple user interface, even a beginner can handle this task.        Get access to all the fe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RawHtmlOverview {
            get {
                return ResourceManager.GetString("RawHtmlOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Editor.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PDF online.
        /// </summary>
        public static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PDF. Add text, comments, highlights.
        /// </summary>
        public static string TitleSub {
            get {
                return ResourceManager.GetString("TitleSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free online PDF document editor.
        /// </summary>
        public static string TitleSub1 {
            get {
                return ResourceManager.GetString("TitleSub1", resourceCulture);
            }
        }
    }
}
