//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspose.PDF.Editor.AppResources.Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SeoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspose.PDF.Editor.AppResources.Editor.SeoResources", typeof(SeoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspose.PDF Editor.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click inside the file drop area to upload a or drag &amp; drop the file..
        /// </summary>
        public static string HowtoFeature1 {
            get {
                return ResourceManager.GetString("HowtoFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File will be automatically rendered for you to view, edit &amp; download instantly..
        /// </summary>
        public static string HowtoFeature2 {
            get {
                return ResourceManager.GetString("HowtoFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the original or edited file..
        /// </summary>
        public static string HowtoFeature3 {
            get {
                return ResourceManager.GetString("HowtoFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert &amp; download the edited file as PDF..
        /// </summary>
        public static string HowtoFeature4 {
            get {
                return ResourceManager.GetString("HowtoFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert &amp; download the edited file as HTML..
        /// </summary>
        public static string HowtoFeature5 {
            get {
                return ResourceManager.GetString("HowtoFeature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://products.aspose.app/img/pdf/HowToExample/Step1.png.
        /// </summary>
        public static string HowtoImageUrlFeature1 {
            get {
                return ResourceManager.GetString("HowtoImageUrlFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://products.aspose.app/img/pdf/HowToExample/Step2.png.
        /// </summary>
        public static string HowtoImageUrlFeature2 {
            get {
                return ResourceManager.GetString("HowtoImageUrlFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://products.aspose.app/img/pdf/HowToExample/Step2.png.
        /// </summary>
        public static string HowtoImageUrlFeature3 {
            get {
                return ResourceManager.GetString("HowtoImageUrlFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://products.aspose.app/img/pdf/HowToExample/Step2.png.
        /// </summary>
        public static string HowtoImageUrlFeature4 {
            get {
                return ResourceManager.GetString("HowtoImageUrlFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://products.aspose.app/img/pdf/HowToExample/Step2.png.
        /// </summary>
        public static string HowtoImageUrlFeature5 {
            get {
                return ResourceManager.GetString("HowtoImageUrlFeature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your PDF file.
        /// </summary>
        public static string HowtoNameFeature1 {
            get {
                return ResourceManager.GetString("HowtoNameFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your rendered result.
        /// </summary>
        public static string HowtoNameFeature2 {
            get {
                return ResourceManager.GetString("HowtoNameFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download or edited file..
        /// </summary>
        public static string HowtoNameFeature3 {
            get {
                return ResourceManager.GetString("HowtoNameFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert &amp; download the edited file as PDF..
        /// </summary>
        public static string HowtoNameFeature4 {
            get {
                return ResourceManager.GetString("HowtoNameFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert &amp; download the edited file as HTML..
        /// </summary>
        public static string HowtoNameFeature5 {
            get {
                return ResourceManager.GetString("HowtoNameFeature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to view, edit and download a PDF file.
        /// </summary>
        public static string HowtoTitle {
            get {
                return ResourceManager.GetString("HowtoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PDF by adding text, shapes, comments and highlights with advanced WYSIWYG edito. Without registration and captcha. It&apos;s secure and private..
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Editor | Online and Free | Aspose.PDF.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
